### ISSUE TITLE
GCP_ZONE and CLUSTER_NAME should be optional for `prepare-gcloud`

### ISSUE THREAD

**Issue by johnhaitas** [reactiveops/rok8s-scripts#127]
When building a container, we do not need to know the GCP_ZONE or CLUSTER_NAME because we are not performing any Kubernetes operations.

could replace https://github.com/reactiveops/rok8s-scripts/blob/a882e04/bin/prepare-gcloud#L31 with the following
```bash
if [[ -n ${CLUSTER_NAME+x} ]] && [[ -n ${GCP_ZONE+x} ]]; then
  gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${GCP_ZONE}" --project "${GCP_PROJECT}"
fi
```

which would require the following change to https://github.com/reactiveops/rok8s-scripts/blob/a882e04/bin/prepare-gcloud#L4-L12
```bash
if [[ -z ${GCP_PROJECT+x} ]] || [[ -z ${GCLOUD_KEY+x} ]]; then
  echo -n "Missing required variable(s):"
  [[ -n ${GCP_PROJECT+x} ]] || echo -n " GCP_PROJECT"
  [[ -n ${GCLOUD_KEY+x} ]] || echo -n " GCLOUD_KEY"
  echo ""
  exit 1
fi
```

**Comment by ejether** [comment]
Thanks for the suggestion @johnhaitas. I'm curious what your use case is here?

**Comment by johnhaitas** [comment]
Building an image and pushing it to Google Container Registry without actually deploying it to a cluster.  This is how we do every single build. I have a small script that is very similar to the `rok8s-scripts` though slightly different in other ways.

Another use case is when building base containers - there is no need to touch a cluster.

**Comment by johnhaitas** [comment]
@ejether i failed to @ mention you in the last message - apologies

**Comment by ejether** [comment]
I see.  
Since we are pretty much always doing a deployment we still need the check and resulting failure if those env vars. They are non-optional in the way we are primarily using `prepare-gcloud` so the modifications you propose won't work, but I can see a way we can do both by modularizing the workflow a bit more and providing another script that logins in to docker. Could that work for your needs?

**Comment by robscott** [comment]
It looks like this functionality was actually added around 7 months ago - sorry we missed updating this issue!
