### ISSUE TITLE
External Secrets are broken with Kubectl 1.10.0

### ISSUE THREAD

**Issue by robscott** [reactiveops/rok8s-scripts#141]
Error received:

```
error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

Importantly this has only been tested with Kubectl 1.10 pointed at a Kubernetes 1.8 cluster at this point.

**Comment by sudermanjr** [comment]
@rob is this still an issue?

**Comment by robscott** [comment]
I think this may have been limited to those specific versions of kubectl and kubernetes. Haven't seen it since that I know of.
