### ISSUE TITLE
Publish Node.js 10 ci-images

### ISSUE THREAD

**Issue by matthewadams** [reactiveops/rok8s-scripts#210]
Hey, can y'all release a ci-image based on Node.js 10 now that Node.js 10 is LTS? The current latest Node image appears to be based on Node.js 8. Until you do, we're having to do the following in our `.gitlab-ci.yml`:
```
.install-nodejs:
  - &install-nodejs |
    echo 'http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories
    apk update
    apk add nodejs=10.14.0-r0
    apk add npm=10.14.0-r0
```
Thanks!

**Comment by robscott** [comment]
Hey @matthewadams, at this point we're trying to move away from language specific ci-images. The goal instead is to run any language specific work in separate containers. These ci-images are intended to simplify building and deploying Docker images to Kubernetes. If there are specific tasks like running tests or precompiling assets that require a specific language, we recommend running them with a different image that. We've decided that it's not the place of these images to try to support every potential image when there are already so many great images available on Docker Hub for language specific tasks. We'll try to make some time to make that more clear in the docs.
