### ISSUE TITLE
Allow passing extra options to helm

### ISSUE THREAD

**Issue by InAnimaTe** [reactiveops/rok8s-scripts#236]
I didn't want to quite go through the work to PR a fix for this because of @robscott's  #235 but I'd like to request the ability to pass extra options to Helm (and really any other binary like `docker`).

i.e. `helm-deploy -f blah.yaml --force --recreate-pods`

**Comment by sudermanjr** [comment]
For Docker build there is an environment variable that allows you to do this.  Not sure if it fits your use-case, but it would be fairly trivial to add a similar variable for helm in the short term.

I don't know where the documentation for it went, but here you can see `ROK8S_DOCKER_BUILD_EXTRAARGS`
https://github.com/reactiveops/rok8s-scripts/blob/b0910fafc463cc2d864138b4458fee8493f268f3/bin/docker-build#L3

**Comment by InAnimaTe** [comment]
Yeah that's similar to what I was thinking; just add in a variable and if its empty, no problem, but if not, it can include a few more options. Is this something I can PR and get approved pretty quickly?

**Comment by sudermanjr** [comment]
Fixed in v7.23.0 by PR #237
