### ISSUE TITLE
Cronjob deployment should use `set image`

### ISSUE THREAD

**Issue by baileymiller182** [reactiveops/rok8s-scripts#257]
Refer to: https://github.com/kubernetes/kubernetes/issues/57393

When `k8s-deploy` deploy cronjobs, it would be ideal if `kubectl set image ...` was called so that new jobs spawned by the updated cronjob used the new image.

**Comment by sudermanjr** [comment]
@baileymiller182 Thanks for the feedback.  I am trying to do some research on this issue, and it seems that the way we do this now (using kubectl apply), handles the image update already.

I tested in a 1.11 cluster by creating a cronjob, modifying the yaml locally to update the image, and then kubectl applying the yaml again. When looking at the cluster, the new runs of the cronjob use the new images.  

Please let me know if I am missing something, but I cannot seem to produce the scenario that you are mentioning.

**Comment by baileymiller182** [comment]
Ok. Not sure why my experience is different. I was on a year+ older version of rok8s-scripts so perhaps there was some change.
