### ISSUE TITLE
HELM_VALUES variable seemingly can't accept multiple values files

### ISSUE THREAD

**Issue by dosullivan** [reactiveops/rok8s-scripts#273]
When using helm with rok8s-scripts, there are scenarios in which it's sometimes useful to apply multiple values yml files to combine configurations. However, this doesn't seem to work within rok8s-scripts config files. Rok8s-scripts will only pick up the first entry for `HELM_VALUES`.

For example, if I have a rok8s-scripts config file that looks like this:
```
NAMESPACE='mynamespace'

HELM_CHARTS=('charts/mychart')
HELM_RELEASE_NAMES=('hpa-mychart')
HELM_VALUES=('values/standard' 'values/production')
HELM_TIMEOUTS=('60')
```

The rok8s-scripts output will look like this:

```
Reading config
Loading configuration from /workdir/deploy/production.config
...
[output omitted]
$HELM_HOME has been configured at /root/.helm.
--
  | Not installing Tiller due to 'client-only' flag having been set
  | Happy Helming!
  | Deploying Helm Charts
  | Applying ./deploy/charts/mychart with ./deploy/values/standard.values.yml
  | No requirements found in /workdir/deploy/charts/mychart/charts.
  | Release "mychart" has been upgraded. Happy Helming!
```

**Comment by sudermanjr** [comment]
I believe what you have to do is set it like this:

```
HELM_VALUES=('values/standard values/production')
```

It treats each quoted string as the set of values files for each helm chart, since we support multiple helm charts.

**Comment by sudermanjr** [comment]
In addition, it's normally common practice to use the default values file in the chart as the "standard" values file, but I understand this doesn't apply in all cases.

**Comment by dosullivan** [comment]
My bad, we had incorrectly formatted it as if we were doing multiple values file for multiple releases! Closing.
