### ISSUE TITLE
kubectl's installation should be cached

### ISSUE THREAD

**Issue by jmound** [reactiveops/rok8s-scripts#31]
...so that it doesn't need to be installed on every build.

**Comment by philipcristiano** [comment]
It seems all that is done on CircleCI is to update `kubectl` on each run. Looking through some CI runs it takes about 10-20 seconds. 

https://github.com/reactiveops/k8s-scripts/blob/adfdd888270face050f8a7b92d11d6a5c15ffc7e/bin/ensure-kubectl#L53

How long are you seeing runs taking?

**Comment by jmound** [comment]
30s. https://circleci.com/gh/reactiveops/krails/180
Not huge, but for a 3:09 build ~1/6 is significant for a developer. 

I'm thinking that just the kubectl bin can be put in to something like ~/. kube (via ensure-kubectl) and then circle can be told to cache that directory across builds. ensure-kubectl can then check for kubectl's existence and perhaps the right version. 

That should get it down to 1s for a cache hit

**Comment by philipcristiano** [comment]
Gotcha. Although there are no tests at the moment so it would likely be longer and not quite 1/6. At the moment the builds I'm working on are ~25, so not quite the biggest issue for them at the moment.

**Comment by robscott** [comment]
Now that we've moved to using ci-images with everything effectively cached, this seems to have been resolved.
