### ISSUE TITLE
version in package.json has fallen behind tagged releases

### ISSUE THREAD

**Issue by sairez** [reactiveops/rok8s-scripts#35]

**Comment by philipcristiano** [comment]
I'm planning to tackle this by removing the version string from the `package.json` in the repo and then using the CircleCI release process to place the tagged version in when it's published. Does that work for you @sairez? It does mean moving to `NPMjs` installation instead of GH though.

**Comment by sairez** [comment]
GH installation will no longer function?

**Comment by philipcristiano** [comment]
Not sure, I may leave a 0.0.0 version in there to allow `sed` to leave it still installable, or replace with some `VERSION_GOES_HERE` string.

**Comment by sairez** [comment]
that would be ideal, until we can phase out github installs across customers

**Comment by philipcristiano** [comment]
The package.json now has `0.0.0` as the version and it is replaced in the build process and uploaded. I'm going to make the packaged version the preferred way to install.

**Comment by philipcristiano** [comment]
Closing as I believe this to be resolved. If it is not, please reopen!
