### ISSUE TITLE
Have the ability to deploy without verification.

### ISSUE THREAD

**Issue by robwar** [reactiveops/rok8s-scripts#40]
Split the deploy script into one that deploys and verifies and one that deploys and moves on.

Zipmark has requested this feature.

**Comment by sairez** [comment]
they want to deploy, but not to wait for it to verify deployment. like an async deployment

**Comment by jmound** [comment]
Would skipping this section [k8s-deploy#L254](https://github.com/reactiveops/k8s-scripts/blob/master/bin/k8s-deploy#L254) work?

If so, we can add a flag for that, I'd think.

**Comment by sairez** [comment]
@jmound yes, essentially. @philipcristiano thought separating the two would be a cleaner implementation so maybe he can speak to his idea.

**Comment by philipcristiano** [comment]
I'd rather make a backwards incompatible release and split the `deploy` and `verify-deployment` tasks into separate scripts and provide a `deploy-and-verify`.

Separate scripts helps avoid a pattern of a single large script with multiple flags to change the flow of control and avoid failing into the [boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap). I think this would be more flexible as well allowing a quick deployment of every service and verify in a specific order for time/importance if needed.

**Comment by philipcristiano** [comment]
This is now in `v4` tagged releases as separate `deploy`, `verify`, and `deploy-and-verify` scripts!
