### ISSUE TITLE
docker-pull pulling 2 images

### ISSUE THREAD

**Issue by pabloroz** [reactiveops/rok8s-scripts#42]
Is there a reason to always try to pull the two images (latest commit and branch) in the docker-pull script or if we find one of them then we don't need to pull the second one?

**Comment by philipcristiano** [comment]
That could certainly be optimized. The use case is for CI systems dealing with branching, the latest commit may not work depending on the number of commits pushed and the branch may not work if it is newly created. 

We will need to rework how pulls/builds work in the near future to take advantage of caching changes in Docker as k8s-scripts won't use caching beyond 1.9
