### ISSUE TITLE
refactor k8s-scripts to make friendly to run on dev workstations

### ISSUE THREAD

**Issue by emalloy** [reactiveops/rok8s-scripts#43]
### develop k8s-scripts to be friendly to run on dev workstations

... and outside circleci, maybe travisci as well.

specifically one snag I can recall: Running  through this with a customer on who was on OSX and was `ensure-kubectl` failing because unmet dependencies keying off `PKG_MANAGER` vs. `$(uname -s)` ... This is just one example. 

Wanted to capture this as a customer of ours has requested. I think and agree it would be more advantageous to test deployments from a workstation vs. constantly taking up cycles in a ci system while developing out deployment configuration(s) 

I will work on this in my spare time, but don't let that hold anyone back if they have better ideas.

**Comment by philipcristiano** [comment]
Which scripts in particular? I'm not sure that making every script run in any environment is worth the effort. I frequently run `k8s-deploy` locally, it only needs the SHA defined and the path to the config file. 

There are minikube related scripts that may help as well, but I haven't used them recently.

**Comment by aviflax** [comment]
Another problem is that k8s-scripts leaves lots of temp files scattered in the project’s local system, including secrets, and those could be accidentally committed to the git repo.

**Comment by philipcristiano** [comment]
Ah yeah, that is a problem. I've used an ignore similar to `deploy/*.yml-*` to avoid any files being checked in. It should really be fixed though to using a proper tmp location for tmp files.
