### ISSUE TITLE
any reason for timeout.sh?

### ISSUE THREAD

**Issue by ajohnstone** [reactiveops/rok8s-scripts#53]
https://linux.die.net/man/1/timeout ?

**Comment by philipcristiano** [comment]
(Added before my time) 

It's included as `timeout` isn't available on other platforms (OSX at least on my system). Including the script allows a consistent usage of the deploy timeout.

**Comment by ajohnstone** [comment]
We have same sort of issues forever having problems between Linux and mac distros with other colleagues.
We've started wrapping things in a container to avoid such issues

**Comment by philipcristiano** [comment]
That's certainly one way to go. At this point I think it's a bit heavyweight to require (on OSX at least) a VM environment to run linux to run docker. Other CI systems also use this including Jenkins in Docker in Kube. 

@ajohnstone Does this answer your question sufficiently?

**Comment by ajohnstone** [comment]
Of course, was more a question out of curiousity
