### ISSUE TITLE
[ensure-kubectl] Timeout downloading cloud SDK Core libraries

### ISSUE THREAD

**Issue by baileymiller182** [reactiveops/rok8s-scripts#79]
ensure-kubectl is timing out when downloading gcloud core libs.

![image](https://user-images.githubusercontent.com/6131507/29428281-7a6e904c-8341-11e7-9ceb-87eed61692b4.png)

**Comment by philipcristiano** [comment]
@baileymiller182 is this something that has just started happening or every time you try to run `ensure-kubectl`? I've tried with a project running on Circle 1.0 and was able to run the command successfully.

**Comment by baileymiller182** [comment]
It happened 2x in a row yesterday, but hasn't happened since. Perhaps Circle or Google just had a networking blip. We can probably close this issue.

**Comment by philipcristiano** [comment]
Sorry you were running into that. That code is a bit before my time but we have been discussing moving to just `wget`'ing the kubectl file which should hopefully be a bit more reliable by not relying on all of `gcloud` to update.
