### ISSUE TITLE
k8s scripts should have integration tests

### ISSUE THREAD

**Issue by ejether** [reactiveops/rok8s-scripts#80]
We should have some way to test the functionality of changes to rok8s scripts so we have confidence that we are not introducing regressions when we add/update the scripts.

**Comment by philipcristiano** [comment]
I'm in the camp for [Integration Tests Are a Scam](http://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam) when it comes to trying to get complete coverage. I had a [pr](https://github.com/reactiveops/rok8s-scripts/pull/32) previously that was experimenting with tests but didn't get much interest (other than @opennomad, thank you for commenting Matthias!). 

One of the challenges with this is testing PRs from non-RO employees. If we intended to test this against any of our resources they we would be allowing arbitrary code execution in our clusters.

**Comment by ejether** [comment]
That argument is good example of the 'slippery slope' logical fallacy and I don't think saying "its hard" is a reason not to do it nor is "we can't get complete coverage". 

Without some sort of functional testing to catch some level of regressions we are at risk of breaking all our customers at once. It happened with a change right when I was working on my first project for Reactiveops.

All PRs from outside will be review before testing. We can create clusters specifically for testing. It doesn't need to happen tomorrow, but I'd like to see it happen.

**Comment by philipcristiano** [comment]
It's partly in regards for regressions. Integration tests are great for smoke testing and making sure at least one happy case exists.
