### ISSUE TITLE
Unable to log into ECS. `cloud-login` relying on environment variable that is not set

### ISSUE THREAD

**Issue by ejether** [reactiveops/rok8s-scripts#87]
The $AWS_ACCESS_KEY_ID environment variable is not set by CircleCI. Only the ~/.aws/config and ~/.aws/credentials files are set. 

https://github.com/reactiveops/rok8s-scripts/blob/master/bin/cloud-login#L9

**Comment by philipcristiano** [comment]
Superset of #84

**Comment by ejether** [comment]
Fixed #84

**Comment by ejether** [comment]
Closed by #83

**Comment by philipcristiano** [comment]
@ejether It looks like using "Fixes ..." on an issue doesn't work across issues :/
