### ISSUE TITLE
return: can only 'return' from a function or sourced script

### ISSUE THREAD

**Issue by jlwynkoop** [reactiveops/rok8s-scripts#89]
When running cloud-login, it generates a warning:
'node_modules/.bin/cloud-login: line 12: return: can only `return' from a function or sourced script'

I believe changing 'return 0' to 'exit 0' would fix the issue but I'm not sure that gives the desired behavior or not.

**Comment by robscott** [comment]
I don't believe this script exists anymore, closing this issue for now.
