### ISSUE TITLE
Bash variable expansion error in prepare-kubectl

### ISSUE THREAD

**Issue by jlwynkoop** [reactiveops/rok8s-scripts#95]
Line 6 in prepare-kubectl generates an error:
node_modules/.bin/prepare-kubectl: line 6: ~/.kube/config: No such file or directory

This appears to be caused because the output file is enclosed in quotes ("${KUBECONFIG:-~/.kube/config}").  Removing the quotes resolves the issue but will cause an error should the ENV variable $KUBECONFIG have a space in it.  Just enclosing $KUBECONFIG in quotes isn't viable as the user may also try to use a tilde.

There seems to be two viable options:
1) remove the quotes and rely on the user to include quotes in $KUBECONFIG if needed
2) Write some complex expansion code to substitute a fully qualified path for the tilde before dumping the config to the file.

I'm submitting a PR for option 1, if we need to go another direction let me know.

**Comment by jlwynkoop** [comment]
Impact is that prepare-kubectl fails to write to ~/.kube/config thus builds fail on the prepare-kubectl step

**Comment by philipcristiano** [comment]
Looks like this was fixed via #98
